## Tensorflow 2.x를 이용한 선형회귀


In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [ ]:
# 독립변수
X = np.array([1, 2, 3], dtype = "float32")

# 종속변수
y = np.array([2, 2.5, 3.5], dtype = "float32")

In [ ]:
# 입력값을 받고 예측 할 Sequentail 객체 생성
model = Sequential()

model.add(Dense(1, input_dim = 1))

model.summary()

# 오차 제곱의 합이 최소가 되는, w,b 를 찾음
model.compile(loss = "mean_squared_error", optimizer = Adam(lr = 0.1))

model.fit(X, y, epochs = 1000)

In [ ]:
# w, b 찾기
print(model.layers[0].get_weights())

# weight
w = model.layers[0].get_weights()[0][0]
print(w)

# bias
b = model.layers[0].get_weights()[1][0]
print(b)

# 예측
print("X가 10일떄 Y =", w * 10 + b)
print("X가 20일떄 Y =", w * 20 + b)

# model로 바로 예측
pred = model.predict([10, 20])
print(pred)

[array([[0.7499997]], dtype=float32), array([1.1666673], dtype=float32)]
[0.7499997]
1.1666673
X가 10일떄 Y = [8.666664]
X가 20일떄 Y = [16.166662]
[[ 8.666664]
 [16.166662]]


## 인공 신경망을 이용한 AND연산
- 76~106


In [ ]:
import numpy as np

In [ ]:
# AND 연산 
X = np.array([ 
          [0, 0],
          [0, 1],
          [1, 0],
          [1, 1]
], dtype = 'float32')

y = np.array([
          [0],
          [0],
          [0],
          [1]
], dtype = 'float32')

# weight
w = np.array([
              [1],
              [2]
], dtype = "float32")

# bias
b = np.array([3], dtype = "float32")

print("X =\n",X)
print("y =\n",y)
print("초기 예측\n", np.dot(X,w) + b)

print("예측값이 3,5,4,6? ")
print("0과 1보다큼,   주로 분류에 사용하는 회귀스틱 분석은 0~1 사이 신호를 가져야함\n\
       따라서 활성화 함수 Sigmoid를 사용 ")

In [ ]:
def sigmoid(h):
  return 1 / (1 + np.exp(-h))

In [ ]:
hypothesis =  sigmoid(np.dot(X,w) + b)

print(X)

X_col_2d1 = X.T[0].reshape(1, -1)
X_col_2d2 = X.T[1].reshape(1, -1)
print(X_col_2d1)
print(X_col_2d2)

# w1 수정값
w1_gred = 1 /4 * np.sum(np.dot(X_col_2d1, (hypothesis -y)))
print("w1_gred:",w1_gred)

# w2 수정값
w2_gred = 1 /4 * np.sum(np.dot(X_col_2d2, (hypothesis -y)))
print("w2_gred:",w2_gred)

# b 수정값
b_gred = 1/4 * np.sum(hypothesis - y)
print("b_gred :",b_gred)

[[0. 0.]
 [0. 1.]
 [1. 0.]
 [1. 1.]]
[[0. 0. 1. 1.]]
[[0. 1. 0. 1.]]
w1_gred: 0.24488529562950134
w2_gred: 0.24770864844322205
b_gred : 0.731355607509613


In [ ]:
learning_rate = 0.1

for i in range(1000):
  for j in range(2):
    hypothesis = sigmoid(np.dot(X, w)+b)
    print("예측값 = ", hypothesis)

    # 오차 계산
    cost = -1/4 * (y * np.log(hypothesis) + (1-y)*np.log(1-hypothesis))
    print("cost = ", cost)

    # 2차원 배열
    X_col_2d = X.T[j].reshape(1,-1)

    # w 기울기 
    w_grad = 1/4*np.sum(np.dot(X_col_2d,(hypothesis - y)))
    print("w_{}grad : {}".format(i,w_grad))

    # w 업데이트
    w[j] = w[j] - learning_rate * w_grad
    print("w{} : {}".format(j,w))
    
    # b 기울기
    b_grad = 1/4 * np.sum(hypothesis - y)
    print("b{}_grad:{}".format(i,b_grad))
    # b 업데이트
    b = b - learning_rate * b_grad
    print("b:{}".format(b))

    print("="*100)

In [ ]:
predict = sigmoid(np.dot(X,w)+b)
predict01 = np.where(predict>=0.5, 1,0)
print("="*50)
print(predict)
print("predict01")
print(predict01)

[[0.00735112]
 [0.13858733]
 [0.13838431]
 [0.77724403]]
predict01
[[0]
 [0]
 [0]
 [1]]


In [ ]:
predict02 = (predict01 == y)
print(y)
print(predict02)

acc = np.sum(predict02)/4
print(acc)

[[0.]
 [0.]
 [0.]
 [1.]]
[[ True]
 [ True]
 [ True]
 [ True]]
1.0


In [ ]:
# 0, 1의 and 연산
arr = np.array([0 ,1], dtype = 'float32')
predict =  sigmoid(np.dot(arr, w) + b)
print(predict)

predict01 = np.where(predict > 0.5 , 1,0)
print("="*50)
print("predict01")
print(predict01)

[0.13858733]
predict01
[0]


In [ ]:
# 1 1의 and 연산
arr = np.array([1 ,1], dtype = 'float32')
predict =  sigmoid(np.dot(arr, w) + b)
print(predict)

predict01 = np.where(predict > 0.5 , 1,0)
print("="*50)
print("predict01")
print(predict01)

[0.77724403]
predict01
[1]
