## 파이썬 합성곱 연산

- 452 ~481

In [ ]:
import numpy as np
from scipy.signal import correlate, correlate2d

In [ ]:
# 배열
x = [2, 8, 3, 7, 1, 2, 0, 4, 5]

# 합성곱 필터
w= [3, 5, 1, 2]

In [ ]:
# 합성곱 연산 - for문 
print("all x:",x)
for i in range(6):
  print("x[{} : {}] = {}".format(i, i+4, x[i : i+4]))
print("=" * 100)

# 합성곱 해보기
for i in range(6):
    print("x[{} : {}] * w ={}".format(i, i+4,  np.dot( x[i:i+4], w)  ))

all x: [2, 8, 3, 7, 1, 2, 0, 4, 5]
x[0 : 4] = [2, 8, 3, 7]
x[1 : 5] = [8, 3, 7, 1]
x[2 : 6] = [3, 7, 1, 2]
x[3 : 7] = [7, 1, 2, 0]
x[4 : 8] = [1, 2, 0, 4]
x[5 : 9] = [2, 0, 4, 5]
x[0 : 4] * w =63
x[1 : 5] * w =48
x[2 : 6] * w =49
x[3 : 7] * w =28
x[4 : 8] * w =21
x[5 : 9] * w =20


In [ ]:
# 위에걸 한방에
print("mode : valid",correlate(x, w, mode = 'valid'))

# 세임패딩 : 출력 배열의 길이를 원본 배열의 길이와 동일하게 만듬
# -> 모서리에 0을 붙임  , 이를 제로패딩을 추가한다라고 함



array([63, 48, 49, 28, 21, 20])

이차원 합성곱 연산 실습

In [ ]:
x = np.array(
                [
                 [1,2,3],
                 [4,5,6],
                 [7,8,9]
                ]
             , dtype="float32")

w = np.array([
              [2,0],
              [0,0]
            ])

In [ ]:
# 그냥 곱하기 - > 원본 배열크기랑 달라짐
print("valid:\n",correlate2d(x, w, mode = 'valid'))

# 패딩추가후 2차원 배열 곱셈
print("same:\n",correlate2d(x, w, mode = 'same'))

valid:
 [[ 2.  4.]
 [ 8. 10.]]
same:
 [[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]


텐서플로를 이용한 합성곱 연산

- 이미지는 4차원 배열
- 텐서플로에서 합성곱 입력(이미지)는 3차원 이미지들이 여러개 있는 4차원 배열

- 가중치(필터)는 3차원 이미지들이 여러개 있는 4차원 배열

In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
import tensorflow as tf
import numpy as np
from scipy.signal import correlate2d
import matplotlib.pyplot as plt

%matplotlib inline

In [ ]:
tf.enable_eager_execution()
tf.__version__

'1.15.2'

In [ ]:
x = np.array(
                [
                 [1,2,3],
                 [4,5,6],
                 [7,8,9]
                ]
             , dtype="float32")

# 타입 변환 
x = np.array(x, dtype = 'float32')
print("x.shape :",x.shape)

# 차원 변환 (개수, 높이 , 너비 , 채널개수)
x =  x.reshape(1, 3, 3, 1)

# reshape 확인
print("x.reshape :",x.shape)

# 가중치(필터)
w = np.array([
              [2,0],
              [0,0]
            ])
# shape 확인
print("w.shape", w.shape)

# 차원 변환(너비, 높이 , 채널,  가중치 개수)
w = w.reshape(2, 2, 1, 1)

# 확인
print("w.reshape",w.shape)

x.shape : (3, 3)
x.reshape : (1, 3, 3, 1)
w.shape (2, 2)
w.reshape (2, 2, 1, 1)


In [ ]:
# 합성곱 연산 수행
conv = tf.nn.conv2d(x ,w, strides =1, padding = 'SAME')
conv

<tf.Tensor: id=2, shape=(1, 3, 3, 1), dtype=float32, numpy=
array([[[[ 2.],
         [ 4.],
         [ 6.]],

        [[ 8.],
         [10.],
         [12.]],

        [[14.],
         [16.],
         [18.]]]], dtype=float32)>

맥스풀링

- 특성맵을 스캔하며 최댓값 고르는 것

In [ ]:
# tf.nn.max_pool2d : MaxPooling
# ksize = 2 : 2줄 2칸을 그룹으로 함
# stride= 1 : 1 칸식 이동하면서 맥스 풀링
# conv : 맥스플링 실행할 배열
tf.nn.max_pool2d(conv, ksize=2, strides=1, padding="VALID")

<tf.Tensor: id=3, shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[10.],
         [12.]],

        [[16.],
         [18.]]]], dtype=float32)>