## 심층신경망을 이용한 XOR (텐서플로 1.x)
- 206 ~ 216

In [ ]:
%tensorflow_version 1.x

TensorFlow 1.x selected.


In [ ]:
import numpy as np
import tensorflow as tf


In [ ]:
tf.enable_eager_execution()
tf.__version__

'1.15.2'

In [ ]:
# X
X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
], dtype = 'float32')

# y
y = np.array([
              [0],
              [1],
              [1],
              [0]
],dtype = 'float32')

# w0
w0 = tf.Variable([
                  [1, 2],
                  [3, 4]
] , dtype="float32")

# w1
w1 = tf.Variable([
                  [5],
                  [6]
], dtype="float32")

# b0
b0 = tf.Variable([
                  [0, 0]
], dtype = 'float32')

# b1
b1 = tf.Variable([
                  [0]
], dtype="float32")

In [ ]:
# 첫번쨰
hypothesis0 = tf.sigmoid(tf.matmul(X , w0) + b0)
print("hypothesis0_sigmoid :\n",hypothesis0)
print("="* 50)

# 두번쨰
hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)
print("hypothesis1_sigmoid :\n",hypothesis1)
print("="* 50)


hypothesis0_sigmoid :
 tf.Tensor(
[[0.5        0.5       ]
 [0.95257413 0.98201376]
 [0.7310586  0.8807971 ]
 [0.98201376 0.99752736]], shape=(4, 2), dtype=float32)
hypothesis1_sigmoid :
 tf.Tensor(
[[0.9959299]
 [0.9999764]
 [0.999869 ]
 [0.9999814]], shape=(4, 1), dtype=float32)


In [ ]:
optimizer = tf.train.AdamOptimizer(0.1)
for step in range(5000):
  with tf.GradientTape() as tape:
    hypothesis0 = tf.sigmoid(tf.matmul(X, w0) +b0)

    hypothesis1 = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)

    cost = -tf.reduce_mean(y * tf.log(hypothesis1) + (1-y) * tf.log(1- hypothesis1))

    grads = tape.gradient(cost, [w0, w1, b0, b1])

    optimizer.apply_gradients(grads_and_vars = zip(grads,[w0, w1, b0, b1]))
    if step % 100 == 0:
      print("cost :{}, w0:{}, w1 : {}".format(cost, w0, w1))

cost :4.0991926193237305, w0:<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[0.9000014, 1.9000086],
       [2.9000015, 3.9000084]], dtype=float32)>, w1 : <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[4.9],
       [5.9]], dtype=float32)>
cost :0.557486355304718, w0:<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.0565379, -4.4126105],
       [ 1.2810545,  3.0600321]], dtype=float32)>, w1 : <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.6855311],
       [3.8502126]], dtype=float32)>
cost :0.5103297233581543, w0:<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.586327 , -6.2746325],
       [ 1.5904139,  4.8805475]], dtype=float32)>, w1 : <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[2.3543897],
       [4.411695 ]], dtype=float32)>
cost :0.49529534578323364, w0:<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-2.8877606, -7.3770695],
  

In [ ]:
# 가중치, 편향 출력
print("w0 : \n",w0)
print("w1 : \n",w1)

print("b0 : \n",b0)
print("b10 : \n",b1)

w0 : 
 <tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ -9.12464 , -12.648861],
       [  9.688222,  12.943744]], dtype=float32)>
w1 : 
 <tf.Variable 'Variable:0' shape=(2, 1) dtype=float32, numpy=
array([[-17.039652],
       [ 17.550508]], dtype=float32)>
b0 : 
 <tf.Variable 'Variable:0' shape=(1, 2) dtype=float32, numpy=array([[ 4.284906 , -7.1995845]], dtype=float32)>
b10 : 
 <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[8.180049]], dtype=float32)>


In [ ]:
# 예측
# 첫번쨰 선형회귀
hypothesis0 = tf.sigmoid(tf.matmul(X, w0) + b0)

# 2번쨰 선형회귀값을 예측값으로
predict = tf.sigmoid(tf.matmul(hypothesis0, w1) +b1)

print("predict = \n",predict)
print("="*  100)

predict01 = tf.cast(predict>0.5, dtype = tf.float32)
print("0.5이상이면 1, 아니면 0 으로 변환 : \n", predict01)
print("="*  100)

# 정답이랑 비교
ac01 = tf.equal(predict01, y)
print("정답이면 True, 아니면 False :\n", ac01)
print("="*  100)

# True,False  ->1,0
ac02 = tf.cast(ac01, dtype = tf.float32)
print("True, False -> 1,0으로 변환 :\n",ac02)
print("="*  100)

# 정확도 구하기 
ac03 = tf.reduce_mean(ac02)
print("정확도:",ac03.numpy())
print("="*  100)

# 위에 과정을 한줄로
accuracy = tf.reduce_mean(tf.cast(tf.equal(predict01, y), dtype = tf.float32))
print("정확도 :",accuracy.numpy())

predict = 
 tf.Tensor(
[[1.8133664e-04]
 [9.9982232e-01]
 [9.9967980e-01]
 [1.6499007e-04]], shape=(4, 1), dtype=float32)
0.5이상이면 1, 아니면 0 으로 변환 : 
 tf.Tensor(
[[0.]
 [1.]
 [1.]
 [0.]], shape=(4, 1), dtype=float32)
정답이면 True, 아니면 False :
 tf.Tensor(
[[ True]
 [ True]
 [ True]
 [ True]], shape=(4, 1), dtype=bool)
True, False -> 1,0으로 변환 :
 tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]], shape=(4, 1), dtype=float32)
정확도: 1.0
정확도 : 1.0


In [ ]:
# 0, 1 XOR 연산
arr = np.array([
                [0,1]
], dtype = "float32")

hypothesis0 =tf.sigmoid(tf.matmul(arr, w0) + b0)

predict = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)

print(predict.numpy())

predict = tf.cast(predict > 0.5,1, 0)
print(predict.numpy())

[[0.9998223]]
[[1.]]


In [ ]:
# 1, 1 XOR 연산
arr = np.array([
                [1,1]
], dtype = "float32")

hypothesis0 =tf.sigmoid(tf.matmul(arr, w0) + b0)

predict = tf.sigmoid(tf.matmul(hypothesis0, w1) + b1)

print(predict.numpy())

predict = tf.cast(predict > 0.5,1, 0)
print(predict.numpy())

[[0.00016499]]
[[0.]]


## 심층신경망을 이용한 XOR (텐서플로 2.x)

- 217 ~ 227

In [ ]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
import numpy as np

In [ ]:
tf.__version__

'2.6.0'

In [ ]:
# X
X = np.array([
              [0, 0],
              [0, 1],
              [1, 0],
              [1, 1]
], dtype = 'float32')

# y
y = np.array(
              [0, 1, 1, 0]
,dtype = 'float32')

In [ ]:
model =  Sequential()

# 출력 데이터는 hypothesis0이고 칸의 수는 2
# input_dim =2 , 입력데이터는 X이고 칸의 수는 2
model.add(Dense(2, input_dim = 2, activation = "sigmoid"))

model.add(Dense(1, activation = 'sigmoid'))

model.summary()

# binary_crossentropy =
# -1/4 * (y * np.log(hypothesis) + (1-y) * np.log(1-hypothesis))
model.compile(loss = 'binary_crossentropy', optimizer = Adam(learning_rate = 0.01), metrics=['acc'])

model.fit(X, y, epochs = 500)

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 2)                 6         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________
Epoch 1/500
1/1 [==============================] - 0s 373ms/step - loss: 0.7197 - acc: 0.5000
Epoch 2/500
1/1 [==============================] - 0s 7ms/step - loss: 0.7168 - acc: 0.5000
Epoch 3/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7141 - acc: 0.5000
Epoch 4/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7115 - acc: 0.5000
Epoch 5/500
1/1 [==============================] - 0s 5ms/step - loss: 0.7091 - acc: 0.5000
Epoch 6/500
1/1 [==============================] - 0s 3ms/st

In [ ]:
# 예측
pred = model.predict(X)
print("pred : \n", pred)
print("="*100)

predict01 = np.where(pred > 0.5, 1, 0)
print("0.5보다 크면 1, 아니면 0 :\n",predict01)
print("="*100)

predict02 = predict01.flatten()
print("1차원 배열로 변환 : ",predict02)
print("="*100)

predict03 = (predict02 == y)
print("맞으면 True, 틀리면 False :", predict03)

# 정확도 계산
acc =np.sum(predict03)/len(predict03)
print("정확도 :",acc)

pred : 
 [[0.0820266 ]
 [0.8528396 ]
 [0.85800016]
 [0.17367616]]
0.5보다 크면 1, 아니면 0 :
 [[0]
 [1]
 [1]
 [0]]
1차원 배열로 변환 :  [0 1 1 0]
맞으면 True, 틀리면 False : [ True  True  True  True]
정확도 : 1.0


In [ ]:
# 0,1 xor 연산
arr =np.array( [ [0, 1]], dtype ="float32")

pred = model.predict(arr)

print(pred)

pred1 = np.where(pred >0.5,1,0)
print("0 XOR 1 = ",pred1)

[[0.8528396]]
0 XOR 1 =  [[1]]


In [ ]:
# 0,1 xor 연산
arr =np.array( [ [1, 1]], dtype ="float32")

pred = model.predict(arr)

print(pred)

pred1 = np.where(pred >0.5,1,0)
print("1 XOR 1 = ",pred1)

[[0.17367616]]
1 XOR 1 =  [[0]]
