In [2]:
from sklearn.datasets import load_iris
import pandas as pd

In [4]:
iris = load_iris()

In [5]:
x_train = iris.data[:-30]

In [7]:
y_train = iris.target[:-30]

In [8]:
y_train

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
x_test = iris.data[-30 : ]

In [10]:
y_test = iris.target[-30 : ]

In [12]:
from sklearn.ensemble import RandomForestClassifier

In [13]:
RandomForestClassifier()

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [15]:
# n_estimators의 default값은 100
# 트리 개수 10개로 설정
rfc = RandomForestClassifier(n_estimators = 10)

In [16]:
rfc.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=10,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [20]:
prediction = rfc.predict(x_test)

In [23]:
prediction

array([2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [19]:
rfc.score(x_test,y_test)

0.8666666666666667

In [25]:
import numpy as np
np.mean(prediction == y_test)

0.8666666666666667

In [ ]:
prediction == y_test

In [27]:
from sklearn.metrics import accuracy_score

In [29]:
accuracy_score(y_test,prediction)

0.8666666666666667

In [30]:
from sklearn.metrics import classification_report

In [32]:
print(classification_report(y_test,prediction))

              precision    recall  f1-score   support

           1       0.00      0.00      0.00         0
           2       1.00      0.87      0.93        30

    accuracy                           0.87        30
   macro avg       0.50      0.43      0.46        30
weighted avg       1.00      0.87      0.93        30



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
confusion_matrix(y_test, prediction)

array([[ 0,  0],
       [ 4, 26]])

In [35]:
prediction

array([2, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [36]:
y_test

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2])

In [37]:
from sklearn.model_selection import train_test_split

In [41]:
x = iris.data
x
y= iris.target


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [50]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size = 0.2)

In [ ]:
X_train

In [51]:
y_test

array([0, 2, 1, 0, 1, 1, 0, 2, 0, 2, 1, 0, 1, 0, 2, 0, 1, 0, 1, 2, 1, 1,
       0, 0, 2, 1, 0, 0, 0, 2])

In [53]:
clf = RandomForestClassifier()
clf

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [55]:
clf = clf.fit(X_train, Y_train)

In [58]:
prediction_1 = clf.predict(X_test)

In [57]:
clf.score(X_test,Y_test)

0.9333333333333333

In [59]:
confusion_matrix(Y_test, prediction_1)

array([[15,  0,  0],
       [ 0,  7,  1],
       [ 0,  1,  6]])

In [60]:
clf_2 = RandomForestClassifier(n_estimators = 200,
                               max_features = 4,
                               oob_score = True
                               )

In [61]:
clf_2

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=4,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [ ]:
# Permutation Importance

# sepal length가 얼마나 중요한지 알고 싶다.
# 1. Sepal length 칸 포함시 분류 성능 - sepal length 제외한 나머지칸의 성능 
# 차가 클수록 중요한 컬럼

In [62]:
clf_2.fit(X_train, Y_train)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features=4,
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=200,
                       n_jobs=None, oob_score=True, random_state=None,
                       verbose=0, warm_start=False)

In [65]:
clf_2.score(X_test, Y_test)

0.9333333333333333

In [70]:
iris.feature_names


['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [66]:
# Sepal length  컬럼의 중요도  = 0.01117734
# sepal length는 있으나 없으나 차이가 거의없음 - >중요핮 않은 컬럼

# 'sepal width' 컬럼의 중요도 = 0.01419674
clf_2.feature_importances_


array([0.01117734, 0.01419674, 0.59421412, 0.3804118 ])

In [73]:
aa = list(zip(iris.feature_names,clf_2.feature_importances_))

In [75]:
for i, percent in aa:
  print(i,percent)

sepal length (cm) 0.01117733991929505
sepal width (cm) 0.014196741832787504
petal length (cm) 0.5942141151305517
petal width (cm) 0.3804118031173658


## 실습

In [93]:
from sklearn.datasets import load_iris
from sklearn.metrics import accuracy_score
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

In [78]:
iris = load_iris()

x_train = iris.data[:-30]
y_train = iris.target[:-30]

x_test = iris.data[-30:]
y_test = iris.target[-30:]

In [105]:
print(y_train)
print("================================================================================")
print(y_test)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2]
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [106]:
rfc = RandomForestClassifier(n_estimators=10)
rfc.fit(x_train,y_train)
prediction = rfc.predict(x_test)
print(prediction ==y_test)

# 분류기 성능 평가(1)
print(rfc.score(x_test, y_test))

# 분류기 성능 평가(2)
print("Accuracy is : ", accuracy_score(prediction, y_test))
print("================================================================================")
print(classification_report(prediction, y_test))

[ True False  True False  True  True False False  True False  True  True
  True False False  True  True  True False  True  True  True  True  True
  True  True  True  True  True  True]
0.7333333333333333
Accuracy is :  0.7333333333333333
              precision    recall  f1-score   support

           1       0.00      0.00      0.00         8
           2       0.73      1.00      0.85        22

    accuracy                           0.73        30
   macro avg       0.37      0.50      0.42        30
weighted avg       0.54      0.73      0.62        30



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [107]:
x = iris.data
y = iris.target
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size =0.2)
print(Y_train)
print("================================================================================")
print(Y_test)

[2 0 0 0 2 2 1 0 0 1 0 2 0 2 2 2 1 0 1 2 2 1 0 2 1 1 1 0 0 2 1 1 0 0 2 1 2
 0 0 2 0 2 2 0 0 2 2 0 0 2 2 1 1 2 0 2 1 1 0 0 2 0 2 2 1 2 0 0 0 1 1 1 0 0
 1 1 2 1 1 1 1 1 2 1 1 1 2 1 2 0 0 2 1 0 2 0 1 0 2 2 1 0 2 0 1 1 1 1 2 0 1
 1 1 0 0 0 2 1 2 1]
[2 1 2 0 2 2 2 0 0 0 1 1 2 2 1 1 0 0 2 1 2 1 0 0 2 2 0 2 0 1]


In [110]:
clf =  RandomForestClassifier()
clf = clf.fit(X_train, Y_train)
prediction_1 = clf.predict(X_test)
print("================================================================================")
print("Accuracy is : ", accuracy_score(prediction_1, Y_test))
print("================================================================================")
print(classification_report(Y_test, prediction_1))
print("================================================================================")

# Random Forest 분류기 성능 높이는 방법
# Tree의 개수 (n_estimators)를 변경   : Tree의 개수를 적당히 확장하면 모듈의 성능을 높일수 있음
# max_features 값 변경

clf_2 = RandomForestClassifier(n_estimators = 200,
                               max_features = 4,
                               oob_score = True

                               )
clf_2.fit(X_train, Y_train)

prediction_2 = clf_2.predict(X_test)
print("Accuracy is : ", accuracy_score(prediction_2, Y_test))
print("================================================================================")
print(classification_report(prediction_2,Y_test))

for feature, imp in zip(iris.feature_names, clf_2.feature_importances_):
  print(feature, imp)
  print("================================================================================")

Accuracy is :  0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.89      1.00      0.94         8
           2       1.00      0.92      0.96        12

    accuracy                           0.97        30
   macro avg       0.96      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

Accuracy is :  0.9666666666666667
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      0.89      0.94         9
           2       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

sepal length (cm) 0.02212170065097399
sepal width (cm) 0.011416052715486702
petal length (cm) 0.4151091206179375
petal width (cm) 0.5513531260156018
